### ISSUE TITLE
Invalid Date - Invalid Date

### ISSUE THREAD

**Issue by ownz21** [LJPc-solutions/freescout-calendar-module#11]
Hello,

I'm utilizing a secret ICS link from Google Calendar to import schedules into Freescout. Seems that all of the entries show up as Invalid Date - Invalid Date, and end up showing every Monday forever. 
![Date Incorrect Screenshot](https://user-images.githubusercontent.com/113247194/189486713-ce4ab5d0-5811-4ece-b824-6335f1f4d431.png)

**Comment by Lars-** [comment]
I use it with Google myself which works as I expect, so it must be something with the secret link. Or maybe some localization issue... Is there a possibility that I can get the link (or another one with the same problem)?

**Comment by ownz21** [comment]
Did you want a link to the calendar or the Freescout instance?

**Comment by ownz21** [comment]
Also, just looking at this some more on my end. Is it possible it's due to the American date format? I've noticed all your date formats are not American standard. This is what the date format looks like from the ics.

DTSTART:20220929T150000Z
DTEND:20220929T230000Z
DTSTAMP:20220910T160619Z

**Comment by Lars-** [comment]
> Did you want a link to the calendar or the Freescout instance?

The calendar



> Also, just looking at this some more on my end. Is it possible it's due to the American date format? I've noticed all your date formats are not American standard. This is what the date format looks like from the ics.
> 
> DTSTART:20220929T150000Z DTEND:20220929T230000Z DTSTAMP:20220910T160619Z

This looks like ISO8601 formatting, which is used in all ics files.

**Comment by ownz21** [comment]
Sent the link to you in the email you have listed on your profile. Just didn't want it to be publicly available. Let me know if you need any additional details.

The entries are being created by a scheduling app called cal.com.

**Comment by Lars-** [comment]
Thanks, I will look at it next week. Probably on Monday or Tuesday

**Comment by Lars-** [comment]
I looked at the issue, it seems that you are using the wrong URL. The URL should look like this: https://calendar.google.com/calendar/ical/[secretkey]/public/basic.ics

When you download it, it should immediately download an ics file. The URL you sent is a link to a shared calendar, but not the ics file.

**Comment by ownz21** [comment]
Hi Lars. I’m sorry I may have sent you the wrong link. I didn’t realize you
wanted the link to the ICS. I’ll send that over to you. My apologies.

**Comment by ownz21** [comment]
I sent it over to your email. Thanks again for your help.

**Comment by ownz21** [comment]
Just wanted to follow up with you Lars. I ended up trying a few things.

- Cleared the tables and removed the plugin and reinstalled it
- Installed the plugin fresh
- Added the google ICS and a standard calendar per your recommendations
- Same results, continued to show the same way

After that I was working on some patching for that same machine and rebooted and all of a sudden it's working now. I do see a bunch of PHP updates  in my patching logs. Not sure if it's related but figured I'd call it out. 

Anyways, I really appreciate you reaching out to me personally and trying to fix this. Still not totally sure what fixed it, but we're all good now. I can't seem to reproduce this anymore.
