### ISSUE TITLE
Name when adding a conversation to the calendar.

### ISSUE THREAD

**Issue by CrazyHenk44** [LJPc-solutions/freescout-calendar-module#15]
In the code (Resources/views/partials/conversation_button.blade.php) I see: 

` <input required="required" type="text" class="form-control" id="calendar-item-title" value="{{$conversation->user? '[' . $conversation->user->getFullName() . '] ': ''}}{{$conversation->getSubject()}}">`

Which I think means de FullName is only added when the conversation is assigned to a user. 
I'm not sure why this is, can't you use the current user for this. If I add a conversation from another user to a calendar, it shows the name of the other user, while I'm the one adding it to the calendar.

Secondly, can we change getFullName() to getFirstName() or use initials from the user, to save some space maybe?

**Comment by Lars-** [comment]
This is because I chose to mention the user that is assigned to the conversation. Most of the times, the assigned user is the one that needs to do something with a calendar entry. Of course it's just a prefill, you can change it to anything you want.
