### ISSUE TITLE
Delete calendar items when the conversation is closed and/or provide a list.

### ISSUE THREAD

**Issue by CrazyHenk44** [LJPc-solutions/freescout-calendar-module#16]
We have a 'ping' calendar, which reminds us to ping customers. Follow up on quotes, renewals, issues or deadlines.

If the customer responds before the ping date, we often close the issue. We have no indication there is still a calendar appointment in the future set.

Can you consider either:

- Adding the calendar entries in the sidebar or at top of the conversation.
- automatically remove the item from the calendar when the conversation is closed (just like kanban does).

Thanks.

**Comment by Lars-** [comment]
Nice to hear that the module is being used. The features sounds cool, but there's little to no time for it right now. Feel free to create it yourself and send a PR. For now I will add it to my "maybe in the future" list.

**Comment by CrazyHenk44** [comment]
Great, everyone is saying to asking a PR nowadays and closing the issue. Great times. I'll switch to a kanban solution or tags with workflow module then. Thanks for considering.

**Comment by Lars-** [comment]
If I had the time or if it was really an issue, I would absolutely fix it, but I really don't have the time to create a new feature that is requested by one person and takes a lot of time, sorry...
