### ISSUE TITLE
guest user can delete calendar item

### ISSUE THREAD

**Issue by riccardofasulo** [LJPc-solutions/freescout-calendar-module#19]
Hi,
Just found that an unlogged user can delete calendar items.
To recreate:
1. as a logged user, create a calendar item
2. as an guest user, go to HTTPS:\\freescoutinstlalation\calendar
3. open the previously created item
4. click on delete

thanks

**Comment by Lars-** [comment]
Yes, that's true, there is nothing to prevent that right now. Feel free to implement it, but I'm also planning to redo the whole module
