### ISSUE TITLE
Connecting calendar entries to tickets?

### ISSUE THREAD

**Issue by jaydio** [LJPc-solutions/freescout-calendar-module#2]
Hi there,

so far love the plugin! However, I think it would be cool to allow calendar events to be associated with tickets. E.g. to realize reminders for customer related activities (e.g. checking on an order at a later date, maintenance schedule commencing and ending etc.).

Cheers

**Comment by Lars-** [comment]
It is already possible to create a new task when you are viewing a conversation. The module adds a new icon to the action bar. It is the last screenshot in the readme. 
![screenshot-6](https://user-images.githubusercontent.com/5690934/147563544-4ed08341-42a5-4120-8584-9a1776d22ba0.jpg)
