### ISSUE TITLE
Overlay of elements in the main page box

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#28]
Hi, when a calendar item's subject is too long, the AM/PM indication goes down a row and is covered by the item's due date indication, as shown in the picture.

![Immagine 2023-06-21 122547](https://github.com/LJPc-solutions/freescout-calendar-module/assets/47970623/00371970-db5e-4373-9b12-adb36eb9e3a3)

is it possible to reduce the fonts of the object preview or take the 12/24H formatting from the system?

Thank you

**Comment by Lars-** [comment]
Yes, that's determined by the translation of the plugin. I use the Dutch locale, so the Dutch translation is used (which is 24h). You can update the translations via Free scout. You would need to change the date format (which is a translatable string).

**Comment by Maddmax76** [comment]
Perfect, I'll try to see how to do it. If it helps, can I provide the translation of the plugin into Italian once done so that you can include it in the project?
Thanks a lot See you soon

**Comment by Maddmax76** [comment]
Forgive me, I followed the instructions to create a translation, in the group I select "Ljpccalendarmodule", I do all the translation and the public, but everything remains unchanged on the homepage.
The only reference to the time is the "hh:mm a" label, does the translation change the format? I tried removing the "a" but it still reads 12h....

**Comment by Lars-** [comment]
Try changing it to "HH:mm" (with capital H), that should change it to 24h format. You can check the Dutch translation for the correct formats: https://github.com/LJPc-solutions/freescout-calendar-module/blob/main/LJPcCalendarModule/Resources/lang/nl.json

**Comment by Maddmax76** [comment]
Set "HH:mm", unfortunately nothing changes....

**Comment by Maddmax76** [comment]
fixed, it works, 
I had file permissions issues which i discovered by reading the logs after trying to share the translations.

Now I have to redo all the work done because it seems to have stored the translations I did at the database level but not in the database..... 

Thanks again, bye

**Comment by Maddmax76** [comment]
the update to 1.3.13 loses the 24h format, even going to the translation management and verifying that the time format entry is HH:mm and publishing the translation, the system displays in 12h format. Do you have any suggestions?

**Comment by Maddmax76** [comment]
I imported the translations again, the Italian translation of the calendar was completely empty, I rewrote it from scratch, I published it, but it continues to display in 12h :-(

**Comment by Lars-** [comment]
That should be related to your installation. You can still create a pull request with the Italian translations. I can then add them to a new release.

**Comment by Maddmax76** [comment]
ok, fixed by adjusting file permissions again.... Thanks again, Ciao!
