### ISSUE TITLE
Additional screenshots and documentation

### ISSUE THREAD

**Issue by fulldecent** [LJPc-solutions/freescout-calendar-module#3]
Congratulations on making a new extension and getting mentioned in the release notes!

Please add additional screenshots, documentation and/or a walkthrough Youtube video to explain more about how this works. This will help people decide if they want to be part of this project.

Specifically I was hoping to see:

- What is the main entrypoint for getting to the calendar?
- Can the calendar be viewed in different timezones?
- Are calendars/calendar items created by one person viewable by other people?

Thank you!

**Comment by Lars-** [comment]
Hi @fulldecent, feel free to contribute.

To answer your questions:
1. Via the menu bar and via the dashboard card
2. No
3. Yes

**Comment by mikk67485** [comment]
Thanks for this great extension.
How can I delete an already added item from the calendar, an item that I no longer need / is no longer relevant
