### ISSUE TITLE
Calendar items don't show on Sundays within the 'Week' view

### ISSUE THREAD

**Issue by herroworrd** [LJPc-solutions/freescout-calendar-module#31]
Within the 'Week' view of the calendar, any items occuring on Sunday will not show. They show fine in the 'Day' and 'Month' views.

**Comment by Lars-** [comment]
Thank you for reporting this. Unfortunately, I don't have the time to debug this issue right now. Sundays work for me, so it sounds like a locale issue.

**Comment by sbbo1** [comment]
We have the same problem, we use DE-DE language.

**Comment by Lars-** [comment]
It is probably fixed in v2. Make sure to make a backup before upgrading and follow the update manual [here](https://github.com/LJPc-solutions/freescout-calendar-module/releases/tag/2.0.0).
