### ISSUE TITLE
deleting calendars?

### ISSUE THREAD

**Issue by SigMarinetti** [LJPc-solutions/freescout-calendar-module#33]
It's probably by design but deleting calendars (not calendar items) seems impossible, i can hide them by removing them from the list, but they still exist and their .ics can be downloaded.

Is there any way to cleanup unwanted calendars?

**Comment by Lars-** [comment]
Hi, I don't know anymore if it is by design that calendars can't be deleted.... The only way to clean them up right now is by editing the database yourself. 

I unfortunately don't have the time to fix it, but I will add it to the list for when I do.
