### ISSUE TITLE
name for external calendars

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#34]
Hi, is there a way to enter a name for external calendars?

when, in calendar management, I insert the link of an external calendar, such as national holidays, I cannot specify the name.
When I view the calendars, in the list of calendars on the left, I only see the colored dot relating to the holiday calendar.
Is there a syntax when entering the URL, to be able to give it a name?

![image](https://github.com/LJPc-solutions/freescout-calendar-module/assets/47970623/0726f21f-93e0-4ace-aec7-9cf45db63631)

![image](https://github.com/LJPc-solutions/freescout-calendar-module/assets/47970623/a0f6329c-4f28-4440-91f3-d53b298cd4b0)

thank you very much

**Comment by Lars-** [comment]
No, there currently isn't. It fetches the name from the ics.
