### ISSUE TITLE
module not working after FreeScout update

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#36]
hi, this morning we applied the FreeScout 1.8.103 update, since then the LJPcCalendar module no longer shows anything, it doesn't draw the calendar, it doesn't show the list of available calendars.

There are no errors in the logs.

You can help us?

**Comment by Maddmax76** [comment]
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-NUbO7FUJVFxYIlFbVqIUPzPPp'". Either the 'unsafe-inline' keyword, a hash ('sha256-uOuigLQo0fpXdTq2haKWyn1c2n6hhF+6oiF/9KBfqJs='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Lars-** [comment]
I noticed the same thing, when I have the time, I will look into it. If you manage to fix it yourself in the meantime, please submit a pull request.

**Comment by Maddmax76** [comment]
I found this while googling, I hope it helps:

"Your CSP is blocking an inline event handler in your HTML code, like <button onclick="myFunction()">Click me</button>.

Inline event handlers are bad practice (mostly because they are inline). See this answer for insight.

Nonce does not seem to work with inline event handlers though. So the best thing to do would be to replace this event handler with a proper one written in your JS file. If you cannot do that, try adding 'unsafe-hashes' to your script-src.

Kudos for rejecting 'unsafe-inline', it's a shortcut we see way too often, including in production."

**Comment by Lars-** [comment]
Fixed in the latest release

**Comment by Maddmax76** [comment]
perfect, installed now, started working again. A thousand thanks!
