### ISSUE TITLE
Adding an Appointment from a Ticket

### ISSUE THREAD

**Issue by sbbo1** [LJPc-solutions/freescout-calendar-module#37]
Since the update to Freescout version 1.8.103 and the update of the calendar module to version 1.3.15, adding an appointment from a ticket unfortunately does not work anymore.

**Comment by Lars-** [comment]
Fixed in 1.3.16

**Comment by Lars-** [comment]
When I have the time, I will look into it again. If you find the solution yourself in the meantime, please send a pull request.

**Comment by Maddmax76** [comment]
hi, I also updated to 1.3.16, but when viewing a ticket, the calendar button doesn't work. Also when I create a new event in the calendar, 10 seconds after saving, the event moves back one hour
