### ISSUE TITLE
events move forward by an hour

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#38]
Hi, despite having updated the module to version 1.3.17, when I create an appointment for 11/15/2023 which goes from 8AM to 7PM, 10 seconds after creation, the appointment in the calendar moves to an hour Before. If I open the appointment in edit, I see that it starts at 7AM and ends at 6PM.
Do you have any idea what it could be?

Thank you

**Comment by Lars-** [comment]
That's not something that has been fixed in the latest updates, that was all related to the csp changes. 
It sounds like a timezone issue, but I have no idea what it could be right now.

**Comment by Maddmax76** [comment]
it seems that the problem already existed before the release of version 1.3.12, I found this request:
[https://github.com/LJPc-solutions/freescout-calendar-module/issues/21](url)
It looks like you solved it by editing the CalendarItem.

**Comment by Lars-** [comment]
Okay, cool, so you can fix it yourself?

**Comment by Maddmax76** [comment]
uhmmmm.... I think I'm very rusty at programming. The last time I tried Joomla php it was still called Mambo!

**Comment by Maddmax76** [comment]
However we did some tests.
If I create an appointment in October BEFORE the daylight saving time change, the appointment time does not change. If I record an appointment in my calendar on a day after the daylight saving time change, the appointment is saved one hour earlier than I set it.
The problem is in the time calculation when I create an appointment for a day with standard time by setting the data while I am on a day with daylight saving time.

**Comment by Maddmax76** [comment]
Hi, have you had a chance to take a look?

**Comment by Lars-** [comment]
Nope, I don't have much time to maintain this module. Whenever I find some time, I will look into it.

**Comment by Maddmax76** [comment]
ok, thanks, in the meantime I avoid making appointments after the change of summer time, bye

**Comment by Lars-** [comment]
It is probably fixed in v2. Make sure to make a backup before upgrading and follow the update manual [here](https://github.com/LJPc-solutions/freescout-calendar-module/releases/tag/2.0.0).

**Comment by Lars-** [comment]
Thanks @Maddmax76, I will add it to the instructions right now.
