### ISSUE TITLE
calendar card doesn't diplay under dasboard

### ISSUE THREAD

**Issue by fdabe** [LJPc-solutions/freescout-calendar-module#39]
Bonjour,

J'ai un soucis au niveau de l'affichage du calendrier sur la dashboard en carte. Au chargement, il se charge puis disparais.
Je ne sais où regarder pourriez vous m'aiguiller svp?

Merci Beaucoup.

Cdlt,

**Comment by fdabe** [comment]
```
<div class="dash-card ljpc_move_dash_card dash-card-calendar" style="display: none;">
    <div class="dash-card-content">
        <h3 class="text-wrap-break "><a href="https://example.com/calendar" class="mailbox-name">Calendrier</a></h3>
        <div class="dash-card-link text-truncate">
            <a href="https://example.com/calendar" class="text-truncate help-link">Actif et à venir</a>
        </div>

        <div class="dash-card-list dash-calendar-contents"></div>
    </div>

```

**Comment by Lars-** [comment]
I'm sorry, I don't speak French.

**Comment by fdabe** [comment]
Good morning,

I have a problem with the calendar display on the map dashboard. When loading, it charges then disappears.
I don't know where to look, could you please direct me?

Thank you so much.

Cdlt,

**Comment by Lars-** [comment]
Hi, that sounds like there aren't any calendars yet. Is that correct?

**Comment by fdabe** [comment]
Yes you're right.
When i suppress the hidden block it appear but when dashboard refresh, it disappaer.
When must i look please.

**Comment by Lars-** [comment]
You have to create a calendar in the settings first.
