### ISSUE TITLE
Can't add events. No error shown.

### ISSUE THREAD

**Issue by apecity** [LJPc-solutions/freescout-calendar-module#40]
Using Freescout 1.8.119. Calendar module 1.3.17.

When I try adding an event, nothing happens.  No error is shown.  Nothing appears in web-server.log when I click Save.  Where else can I look for the cause of this problem?

Module is in /var/www/html/Modules/LJPcCalendarModule

After unzipping it, I also ran "chown -R www-data:www-data /var/www/html/Modules/LJPcCalendarModule".  Was that correct?  Then I activated the module.  Anything else I need to do?

**Comment by Lars-** [comment]
Maybe take a look at the xhr request that is being sent when you add an event, maybe you see something there?

**Comment by apecity** [comment]
I tried using Fiddler, but when I click to save a new calendar event, there
is no web traffic generated.

Do I have to connect a calendar URL in the module's config page first?  I
haven't yet, and that might explain this.

**Comment by Lars-** [comment]
Using fiddler is a bit overkill, the inspect module in every browser would be enough. And yes, you do need to add a calendar first, but not a url. You can only add to calendars that are local. So simply adding a name to the settings will add a calendar.
