### ISSUE TITLE
Handling .ics files, nothing seems to happen.

### ISSUE THREAD

**Issue by apecity** [LJPc-solutions/freescout-calendar-module#41]
Using Freescout 1.8.119, calendar 1.3.17.

I was hoping the module would be able to work with .ics files Freescout receives as attachments.   Like when I receive one in Freescout, I could click on it and add it to my calendar.

It doesn't seem to do anything with them (see attached).  Should it?

https://github.com/LJPc-solutions/freescout-calendar-module/assets/18216162/38aa33d4-7a63-44bc-82a9-2f115f67ee9c

**Comment by Lars-** [comment]
No, that is not something that is build into this module. I do think it would be a nice feature though, so I will add it to the list for when I am going to rebuild the module.

**Comment by apecity** [comment]
Thank you!
