### ISSUE TITLE
calendar access control

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#42]
Hi, is there a way to attach a calendar to a mailbox? If I wanted to create departmental accounts, with user permissions on the Freescout mailboxes, I can make sure that the users of the "Administration and Finance" mailbox do not see the "Logistics" mailbox and vice versa, but the calendars are visible to anyone who enters . It would be useful if, in the module settings, you could assign the calendar to the mailbox, or disable the module for certain users, for example making it visible only to administrators and not to operators.
Is such a configuration possible?
Thank you

**Comment by Lars-** [comment]
That would indeed be very handy, but unfortunately not possible at the moment. I will add it to the list for when I have time to rebuild the whole module.
