### ISSUE TITLE
No longer works with Outlook Error 28

### ISSUE THREAD

**Issue by silicahd** [LJPc-solutions/freescout-calendar-module#44]
When trying to import in outlook via Subscribe from Web.

`{

    "NewFolderId": null,

    "NewCalendarEntryId": null,

    "WasSuccessful": false,

    "ErrorCode": 28

}`

Error code 28 usually indicates that the file format is not supported or is invalid. 

https://answers.microsoft.com/en-us/outlook_com/forum/all/unable-to-import-calendar-in-outlook-live-by/484a4012-7b99-4c9c-8932-02b2f0e6d29c

**Comment by Lars-** [comment]
It’s a basic ICS format, that works in Google Calendar. I don’t know what Microsoft does with it, but it certainly is valid.

**Comment by silicahd** [comment]
Thank you I found the issue. Outlook can only import iCal format for stream but ics format for manual import. I will need to make a change to the module to get this to work. I was going that route anyways as I changes some things to make it mobile friendly. 

Thank you for the great module. Will buy you a coffee for the great work.

**Comment by Lars-** [comment]
Good to hear! And I suggest waiting a bit, I was planning a complete rebuild of the module next week 😊
