### ISSUE TITLE
Cpanel CalDav

### ISSUE THREAD

**Issue by marcomarinho** [LJPc-solutions/freescout-calendar-module#48]
Trying to configure cpanel caldav doesn't seem to work.
Could not resolve host: mail.xxx.xx: at /www/html/Modules/LJPcCalendarModule/vendor/sabre/http/lib/Client.php:356)

**Comment by Lars-** [comment]
Could not resolve host sounds like a DNS issue, so that would not have anything to do with this extension. Try pinging the host via the machine that freescout is running on.
