### ISSUE TITLE
Day in Freescout Kalender ist 23. Day in ICS Imported Kalender is 22 - wrong Date in ICS

### ISSUE THREAD

**Issue by tecwood** [LJPc-solutions/freescout-calendar-module#49]
Hey there,

i added a new calendar entry on 23.08.

if i look at my outlook calendar now (ICS) instead of 23.08 there is now 22.8

can you help me with this problem?

Regards

**Comment by Lars-** [comment]
Hi, 

It's probably a timezone issue. Is the timezone in Freescout the same as where you live? If it is, you should take a look at the contents of the ICS file to check what date is associated to the item.

**Comment by tecwood** [comment]
![Screenshot 2024-08-22 100753](https://github.com/user-attachments/assets/d67e559a-f79a-456f-93be-3ee61602bc07)

ICS:

SUMMARY:freee
DESCRIPTION:
LOCATION:
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTART;VALUE=DATE:**20240821**
DTEND;VALUE=DATE:**20240822**
END:VEVENT
END:VCALENDAR

**Comment by tecwood** [comment]
![image](https://github.com/user-attachments/assets/32cf4945-8147-433f-883f-a2b3bed6a920)

**Comment by Lars-** [comment]
What timezone do you use in Freescout? You can find that by editing your profile. I also would like to know the timezone that you see at: [your freescout url]/system/status

**Comment by tecwood** [comment]
![image](https://github.com/user-attachments/assets/920ab5a9-97a7-4f48-92a3-3817384fc449)

![image](https://github.com/user-attachments/assets/f7ab2c9d-c8db-43e4-a3bb-6960889f25e4)

**Comment by Lars-** [comment]
Thank you for the info. I will look into it next week.
