### ISSUE TITLE
Error during migration from 1.3.7 to 2.0

### ISSUE THREAD

**Issue by it-boerner** [LJPc-solutions/freescout-calendar-module#51]
I have performed the migration, but I always get the following error:

![image](https://github.com/user-attachments/assets/4c55db89-bb3f-46af-be10-d38284576c20)

Furthermore, the following error is displayed in the administration under System. I'm not sure what else I can do. I would probably have to delete the column, but I don't currently know how and whether this would be correct.

![image](https://github.com/user-attachments/assets/54a283a9-3064-4f11-9815-54f3a0b063b7)

**Comment by Lars-** [comment]
It looks like the migrations for 1.3.7 are not correctly done or something went wrong the first time when trying to migrate to 2.0. Either way, you should try the following steps:

1. Restore the calendars and migrations table from your backup
2. Try the migration again

Let me know if that solves it. If it doesn't, you can manually try to revert the migration by looking at the code and simply do the migration backwards. If that also doesn't work, the only option that I can think of is to start fresh with v2.

**Comment by it-boerner** [comment]
I have already deleted all files several times and also tried to install only version 2.0. The problem seems to lie in the database, as this data cannot be deleted.

**Comment by Lars-** [comment]
Why can't the data be deleted?

**Comment by it-boerner** [comment]
Because I do not know how to delete this data from the database.

As you can see in my pictures, there is an error with existing data that obviously cannot be deleted or overwritten by the migration.

**Comment by Lars-** [comment]
Do you have access to the database via some sort of IDE or PHPMyAdmin?

**Comment by it-boerner** [comment]
my system is installed on ubuntu without interface.

there is no php my admin and i don't know where the database is stored.

**Comment by Lars-** [comment]
I can't assist in running your self hosted freescout for free unfortunately. If you would like a managed freescout hosting, I can help with that. My company hosts multiple freescout instances for multiple clients. If you want to host it yourself, I suggest looking up (or asking any LLM) how to get access to the database and then restoring the backup that you (should have) made before migrating to 2.0

**Comment by it-boerner** [comment]
Unbelievable this answer

**Comment by Lars-** [comment]
I'm afraid I can't assist further if you don't have access to the database. Without direct database access, it's not possible to safely resolve the migration issue you're experiencing. If you're not comfortable with database management, you might want to consider using a managed Freescout hosting service. These typically handle migrations and database issues for you, which can save time and reduce risks.
