### ISSUE TITLE
Clearing cache after upgrade

### ISSUE THREAD

**Issue by semaf** [LJPc-solutions/freescout-calendar-module#52]
Hey,

Have followed your update instructions but after clearing the cache it seems that css classes cant be loaded.

There are no errors on console. No logs about error according calendar. Any way to debug?

**Comment by Lars-** [comment]
Hi,

Maybe run `php artisan freescout:after-app-update`. That builds all css and js.
If that doesn't work, maybe try running `php artisan freescout:module-build`

If that also doesn't work, I need some screenshots of the problem.

**Comment by semaf** [comment]
Thank you. Seems that artisan is not installed with freescout docker container. Have to sort this out.
