### ISSUE TITLE
Incorrect month name in calendar month view

### ISSUE THREAD

**Issue by Maddmax76** [LJPc-solutions/freescout-calendar-module#53]
Hi Lars, good morning.
Congratulations on the great work done with the module, you made it really very functional and modern.
I just updated to the latest version, I find the Day/Week/Month view very useful.
Unfortunately I noticed that in the month view, the name of the month is wrong, it displays the name of the last month instead of the current one.

For example, in day view the date is September 11, 2024
in week view it displays September 9, 2024 - September 15, 2024
in month view it shows August 2024 in the header and the calendar with the days of September.

I tried to clear the cache but I see that it does not change, I think it is in the code.

**Comment by Lars-** [comment]
> Congratulations on the great work done with the module, you made it really very functional and modern.
Thanks!

Also thank you for reporting the issue. I think the month is based on the first day in the calendar. Since the first day in the month view for september is 26th of August, it says August. Try finding June.... I will try to fix it today.

**Comment by Lars-** [comment]
Fixed in 2.1.1!

**Comment by Maddmax76** [comment]
fixed.
Great job!
Thanks again
