### ISSUE TITLE
Download of the ics File

### ISSUE THREAD

**Issue by sbbo1** [LJPc-solutions/freescout-calendar-module#54]
We no longer have the possibility to download the ICS files.
Only the possibility to add the ICS file with calendar modules

**Comment by Lars-** [comment]
That is not correct, you can still download the ICS in two ways. You can find the links in the calendar settings.

**Comment by sbbo1** [comment]
I don't think I explained that correctly.
We are talking about ICS files attached to an e-mail.

Previously there was a download button next to the ICS file, now it just says “add meeting.ics to a calendar”

![image](https://github.com/user-attachments/assets/27ca95ec-73da-4ed5-af28-56f41800f47d)

**Comment by Lars-** [comment]
I see now that I misunderstood your initial inquiry. You're correct about the current behavior of the download button for ICS files.

While we don't have immediate plans to change this functionality, you have the option to modify this yourself by changing the code. As the system is customizable, you can implement a setting to disable the replacement of ICS files.

For users with the Extended Attachments module, downloading is still possible via the sidebar or the "Download All" button.

**Comment by sbbo1** [comment]
Unfortunately, this does not work with the extendet attachments module either. The ICS file is not recognized as an attachment.

![image](https://github.com/user-attachments/assets/02e7829a-54ce-447b-80bf-c63b2dce1576)

**Comment by Lars-** [comment]
Fixed in 2.1.5!
