### ISSUE TITLE
Module installed but not added to settings

### ISSUE THREAD

**Issue by p0welly** [LJPc-solutions/freescout-calendar-module#55]
The module downloaded from GitHub and uploaded via ftp to the Modules folder.

Activated via Manage Modules and shows as active

![image](https://github.com/user-attachments/assets/634302fb-f857-426e-82db-e1ce456abad4)

This has not however added anything to the settings menu as show in the video

![image](https://github.com/user-attachments/assets/9d26e0f2-3243-4e3f-a820-ca24fd22f680)

**Comment by Lars-** [comment]
Since I use it myself and it works here, as well as in my test environment, it should be something in your setup. What version of freescout and php do you use and how is freescout hosted?

**Comment by p0welly** [comment]
Freescout 1.8.153
PHP 8 (also tried 7.4)

Hosted on 20i.com using their one click installer

**Comment by Lars-** [comment]
I have tested everything with PHP8.3. Can you test that as well? I’m not familiar with 20i, do they use docker or can you actually reach all the freescout files via (s)ftp or something like that?
