### ISSUE TITLE
Remove "Required" checkbox in settings for custom field type "Source"

### ISSUE THREAD

**Issue by ret1** [LJPc-solutions/freescout-calendar-module#56]
Hi everyone!

If a custom field type named “Source” is set as required, an error occurs when someone attempts to create a calendar entry through a ticket. The browser console displays a message indicating that “Ticketnummer” is a required field (assuming the source field is named “Ticketnummer”).

Since a source field is always added, regardless of whether it is marked as required, there is no need for a “Required” checkbox in this case.

BR
Thomas

**Comment by Lars-** [comment]
Thanks for reporting this issue! Feel free to send a PR for this if you can't wait for a fix, I will try to fix it myself next month.

**Comment by ret1** [comment]
Hi Lars!

Thanks for the fast reply. No hurry on my side. It would be perfectly fine, if you fix it next month.

BR
Thomas

**Comment by Lars-** [comment]
Fixed in 2.1.2!
