### ISSUE TITLE
Calendar module blocks chat module

### ISSUE THREAD

**Issue by PaulBartelings** [LJPc-solutions/freescout-calendar-module#58]

**Comment by PaulBartelings** [comment]
Hi Lars,
After installation of your module my chat widget wont work.  I deleted my post so I think you fixed the problem. Do you have a update?

Greats Paul

**Comment by Lars-** [comment]
Hi Paul, I closed the issue because it is fixed: https://github.com/LJPc-solutions/freescout-calendar-module/issues/57
