### ISSUE TITLE
Upcoming Events in Widget on Dashboard

### ISSUE THREAD

**Issue by szucher** [LJPc-solutions/freescout-calendar-module#59]
Hi,

in the description you write, that the next 10 upcoming events are shown in the dashboard widget. At my freescout installation it shows only the next 3 upcoming events. I can´t find no option that the widget shows more events. 

Is this possible?

Kind regards,
Steffen

**Comment by Lars-** [comment]
@szucher that is absolutely a mistake. It indeed shows 3 events. I will change it immediately in the description, thanks for mentioning it!
