### ISSUE TITLE
How can I delete an already added item from the calendar

### ISSUE THREAD

**Issue by mikk67485** [LJPc-solutions/freescout-calendar-module#6]
Thanks for this great extension.
How can I delete an already added item from the calendar, an item that I no longer need / is no longer relevant

Thanks

**Comment by Lars-** [comment]
Well, just click the item and then delete.
If it's an imported calendar, you can delete it at the source.

**Comment by mikk67485** [comment]
not working. there is no delete button / delete function

**Comment by mikk67485** [comment]
not working. there is no delete button / delete function

**Comment by Lars-** [comment]
I'm 100% sure there is a delete button. I just checked it. Just click on the event you want to delete, a small popup appears with all the information with a delete button in the bottom right. If you don't see it, you probably imported the calendar via an ICS sync in which case you need to delete the event in the source.
