### ISSUE TITLE
cannot add new calendar items

### ISSUE THREAD

**Issue by GreenSmart01** [LJPc-solutions/freescout-calendar-module#60]
when I click on the agenda icon from a ticket to add the ticket as an agenda appointment I get the message "An error has occurred. Check your internet connection and try again."

logs:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'custom_fields_mapping' in 'INSERT INTO' (SQL: insert into `calendar_items` (`calendar_id`, `title`, `start`, `end`, `is_all_day`, `location`, `body`, `custom_fields`, `custom_fields_mapping`, `updated_at`, `created_at`) values
//

**Comment by Lars-** [comment]
Hi!

Did you upgrade from version 1 by any chance? And did you run the latest migrations? 

The error message looks like some migrations didn’t run (properly).

**Comment by GreenSmart01** [comment]
Hi :)
yes i did, how can i run the migrations again?
Thanks inadvance

**Comment by Lars-** [comment]
Maybe try deactivating and then reactivating the module. If that doesn’t work, please share your migrations table content.

**Comment by GreenSmart01** [comment]
I did deactivate and activate the module still the same error.
When I add an appointment manual to the calander it works. Only adding an ticket tot the calander gives me the error.
Can u explain how I can share the migration table?

**Comment by Lars-** [comment]
That’s weird, but okay, we should be able to fix it.

Just go into your database and export the migration table as sql and then share it here.

**Comment by Lars-** [comment]
I've had multiple tickets about the docker variant and the update to version 2. So I guess there is something not working the same way in the Docker environment as in the non-docker environment. I suggest reaching out to freescout for getting access to your database. Let me know when you have access, then we can check if all migrations ran correctly.

**Comment by GreenSmart01** [comment]
Im in the docker database of the freescout mariadb
the latest data in the migrations table is;

`| 100 | 2021_10_11_010101_create_kn_boards_table                                  |    17 |
| 101 | 2021_10_11_020202_create_kn_cards_table                                   |    17 |
| 102 | 2019_11_30_083213_create_custom_fields_table                              |    18 |
| 103 | 2019_12_02_083213_create_conversation_custom_field_table                  |    18 |
| 104 | 2022_09_30_010101_change_options_column_in_custom_fields_table            |    18 |
| 105 | 2022_10_26_010101_add_show_in_list_column_to_custom_fields_table          |    18 |
| 106 | 2023_11_14_010101_change_aliases_column_in_mailboxes_table                |    19 |
| 107 | 2019_12_12_110003_create_workflows_table                                  |    20 |
| 108 | 2020_01_01_101530_create_conversation_workflow_table                      |    20 |
| 109 | 2023_08_29_010101_add_max_executions_column_to_workflows_table            |    20 |
| 110 | 2023_08_29_020202_add_counter_column_to_conversation_workflow_table       |    20 |
| 111 | 2024_06_18_010101_add_index_to_threads_table                              |    21 |
| 112 | 2024_11_03_010101_add_global_column_to_saved_replies_table                |    22 |
| 113 | 2024_04_21_082300_update_calendars_table                                  |    23 |
| 114 | 2024_09_09_112700_update_calendar_items_table                             |    23 |
| 115 | 2023_03_28_181319_add_chatgpt_column_to_threads_table                     |    24 |
| 116 | 2023_05_06_182413_create_hostetskigpt_table                               |    24 |
| 117 | 2023_06_03_142517_change_start_message_column_in_hostetskigpt_table       |    24 |
| 118 | 2023_06_07_222723_add_primary_key_to_hostetskigpt_table                   |    24 |
| 119 | 2023_06_29_221132_add_client_data_enabled_column_to_hostetskigpt_table    |    24 |
| 120 | 2023_06_30_115147_change_chatgpt_column_in_threads_table                  |    24 |
+-----+---------------------------------------------------------------------------+-------+`

**Comment by Lars-** [comment]
I'm planning to release a new version this week, but if you can't wait. Please apply the change yourself in the commit I just pushed.
