### ISSUE TITLE
Blanco frontpage with https://outlook.office365.com/owa/calendar/ in widget.

### ISSUE THREAD

**Issue by PaulBartelings** [LJPc-solutions/freescout-calendar-module#61]
Good morning, since today I no longer have a homepage in Freescout when the calendar module is activated, and I am using an Outlook calendar.
https://outlook.office365.com/owa/calendar/

When I only display my Google Calendar in the widget, everything works fine, but as soon as I try to show my Outlook calendar, I get a completely blank page.

**Comment by Lars-** [comment]
Hi Paul,

That is a weird issue. 

1. Are there some weird tags or strings in the title of one of the upcoming events?
2. Can you find anything in the logs related to this?
3. Is it possible to send the ICS in storage/app/ljpccalendarmodule/[calendar id].ics? (please mail it to support@ljpc.nl if it has any sensitive information)

**Comment by PaulBartelings** [comment]
I'll get back to you.

**Comment by PaulBartelings** [comment]
Hi Lars, today I wanted to reproduce the problem for you, and I reactivated my office calendar, and the issue no longer occurs. As soon as it happens again, I will let you know.
